algoritmo "QUESTAO 06"

var

base: real
altura: real
resultado: real

inicio

escreva("Vamos calcular a área de um retângulo?")
escreval()

escreva("Digite o valor da base: ")
leia(base)
escreval()

escreva("Agora digite o valor da altura: ")
leia(altura)
escreval()

resultado:= base * altura

escreva("A partir dos valores informados o seu retângulo possui uma área de: ",resultado,"m²")


fimalgoritmo